package main

import (
	"bytes"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/charmbracelet/huh"
)

var (
	initGetEUID                    = func() int { return os.Geteuid() }
	initWriteFile                  = writeFileAtomic
	initMkdirAll                   = os.MkdirAll
	initStat                       = os.Stat
	initRunForm                    = func(f *huh.Form) error { return f.Run() }
	initCollectAnswers             = collectInitAnswers
	initConfirmOverwrite           = confirmOverwrite
	initRandomReader     io.Reader = rand.Reader
	initRemoveFile                 = os.Remove
	initStdout           io.Writer = os.Stdout
)

func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	temp, err := os.CreateTemp(filepath.Dir(path), ".ratatosk-*.tmp")
	if err != nil {
		return err
	}
	tempPath := temp.Name()
	defer os.Remove(tempPath)
	if err := temp.Chmod(perm); err != nil {
		temp.Close()
		return err
	}
	if _, err := temp.Write(data); err != nil {
		temp.Close()
		return err
	}
	if err := temp.Sync(); err != nil {
		temp.Close()
		return err
	}
	if err := temp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tempPath, path); err != nil {
		return err
	}
	return os.Chmod(path, perm)
}

func confirmOverwrite(path string) (bool, error) {
	var overwrite bool
	form := huh.NewForm(
		huh.NewGroup(
			huh.NewConfirm().
				Title(fmt.Sprintf("Config file already exists at %s. Overwrite?", path)).
				Affirmative("Yes").
				Negative("No").
				Value(&overwrite),
		),
	)
	if err := initRunForm(form); err != nil {
		return false, err
	}
	return overwrite, nil
}

type initAnswers struct {
	BaseDomain       string
	TLSAuto          bool
	TLSEmail         string
	TLSProvider      string
	TLSAPIToken      string
	RemoteControl    bool
	ControlTokenFile string
}

const configTemplate = `# Ratatosk Relay Server Configuration
# Generated by: ratatosk-server init
# Full reference: https://ragnarok22.github.io/ratatosk/reference/configuration

base_domain: {{ printf "%q" .BaseDomain }}
public_port: {{ if .TLSAuto }}443{{ else }}8080{{ end }}
# The admin dashboard stays local-only by default.
admin_host: 127.0.0.1
admin_port: 8081
{{ if .RemoteControl }}# Remote control plane secured by a generated token and public automatic TLS
control_host: 0.0.0.0
control_port: 7000
control_tls_enabled: true
control_tls_cert_file: ""
control_tls_key_file: ""
control_token_file: {{ printf "%q" .ControlTokenFile }}
{{ else }}# Local plaintext control plane
control_host: 127.0.0.1
control_port: 7000
control_tls_enabled: false
control_tls_cert_file: ""
control_tls_key_file: ""
control_token_file: ""
{{ end }}
{{ if .TLSAuto }}
# Automatic TLS via Let's Encrypt DNS-01 (managed by certmagic)
tls_auto: true
tls_email: {{ printf "%q" .TLSEmail }}
tls_provider: {{ printf "%q" .TLSProvider }}
tls_api_token: {{ printf "%q" .TLSAPIToken }}
{{ else }}
# TLS is disabled. To enable automatic TLS, run 'ratatosk-server init' again
# or edit this file manually.
# See: https://ragnarok22.github.io/ratatosk/guide/deployment
tls_auto: false
{{ end }}# Port range for TCP/UDP tunnel allocation
port_range_start: 10000
port_range_end: 20000
`

var initConfigTmpl = template.Must(template.New("config").Parse(configTemplate))

func renderConfig(tmpl *template.Template, answers initAnswers) ([]byte, error) {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, answers); err != nil {
		return nil, fmt.Errorf("rendering config: %w", err)
	}
	return buf.Bytes(), nil
}

func validateDomain(s string) error {
	s = strings.TrimSpace(s)
	if s == "" {
		return fmt.Errorf("domain is required")
	}
	if !strings.Contains(s, ".") {
		return fmt.Errorf("enter a valid domain (e.g., tunnel.example.com)")
	}
	return nil
}

func validateEmail(s string) error {
	s = strings.TrimSpace(s)
	if s == "" {
		return fmt.Errorf("email is required for Let's Encrypt")
	}
	if !strings.Contains(s, "@") {
		return fmt.Errorf("enter a valid email address")
	}
	return nil
}

func validateAPIToken(s string) error {
	if strings.TrimSpace(s) == "" {
		return fmt.Errorf("API token is required for automatic TLS")
	}
	return nil
}

func canExposeControlRemotely(answers initAnswers) bool {
	return answers.TLSAuto && validateDomain(answers.BaseDomain) == nil
}

func generateControlToken(reader io.Reader) (string, error) {
	random := make([]byte, 32)
	if _, err := io.ReadFull(reader, random); err != nil {
		return "", fmt.Errorf("reading random bytes: %w", err)
	}
	return base64.StdEncoding.EncodeToString(random), nil
}

func configDir() string {
	if initGetEUID() == 0 {
		return "/etc/ratatosk"
	}
	return "."
}

func collectInitAnswers(answers *initAnswers) error {
	form := huh.NewForm(
		huh.NewGroup(
			huh.NewInput().
				Title("What is your base domain?").
				Description("Tunnels will be accessible at <subdomain>.<domain>").
				Placeholder("tunnel.example.com").
				Value(&answers.BaseDomain).
				Validate(validateDomain),
		),
		huh.NewGroup(
			huh.NewConfirm().
				Title("Enable automatic wildcard TLS via Let's Encrypt?").
				Description("Highly recommended for production. Requires a Cloudflare API token.").
				Affirmative("Yes").
				Negative("No").
				Value(&answers.TLSAuto),
		),
		huh.NewGroup(
			huh.NewInput().
				Title("What is your email address?").
				Description("Used for Let's Encrypt certificate expiry notices").
				Placeholder("you@example.com").
				Value(&answers.TLSEmail).
				Validate(validateEmail),
			huh.NewSelect[string]().
				Title("Select your DNS provider").
				Description("Used to solve DNS-01 challenges for wildcard certificates").
				Options(
					huh.NewOption("Cloudflare", "cloudflare"),
				).
				Value(&answers.TLSProvider),
			huh.NewInput().
				Title("Paste your API token for the DNS provider").
				Description("For Cloudflare: create a token with Zone:DNS:Edit permissions").
				EchoMode(huh.EchoModePassword).
				Value(&answers.TLSAPIToken).
				Validate(validateAPIToken),
		).WithHideFunc(func() bool { return !answers.TLSAuto }),
		huh.NewGroup(
			huh.NewConfirm().
				Title("Expose the control plane to remote clients?").
				Description("Production mode: binds publicly with a generated token and automatic TLS.").
				Affirmative("Yes").
				Negative("No").
				Value(&answers.RemoteControl),
		).WithHideFunc(func() bool { return !canExposeControlRemotely(*answers) }),
	)

	return initRunForm(form)
}

func runInit() int {
	fmt.Fprintln(initStdout, "")
	fmt.Fprintln(initStdout, "  Ratatosk Server Setup Wizard")
	fmt.Fprintln(initStdout, "  ============================")
	fmt.Fprintln(initStdout, "")

	var answers initAnswers

	if err := initCollectAnswers(&answers); err != nil {
		if err == huh.ErrUserAborted {
			fmt.Fprintln(initStdout, "\n  Setup cancelled.")
			return 0
		}
		fmt.Fprintf(initStdout, "\n  Error: %v\n", err)
		return 1
	}

	answers.BaseDomain = strings.TrimSpace(answers.BaseDomain)
	answers.TLSEmail = strings.TrimSpace(answers.TLSEmail)
	answers.TLSAPIToken = strings.TrimSpace(answers.TLSAPIToken)
	if !canExposeControlRemotely(answers) {
		answers.RemoteControl = false
	}

	dir := configDir()
	outPath := filepath.Join(dir, "ratatosk.yaml")
	if answers.RemoteControl {
		answers.ControlTokenFile = filepath.Join(dir, "control-token")
	}

	if _, err := initStat(outPath); err == nil {
		overwrite, err := initConfirmOverwrite(outPath)
		if err != nil {
			fmt.Fprintf(initStdout, "\n  Error: %v\n", err)
			return 1
		}
		if !overwrite {
			fmt.Fprintln(initStdout, "\n  Keeping existing config file.")
			return 0
		}
	}

	var tokenData []byte
	if answers.RemoteControl {
		token, err := generateControlToken(initRandomReader)
		if err != nil {
			fmt.Fprintf(initStdout, "\n  Error generating control token: %v\n", err)
			return 1
		}
		tokenData = []byte(token + "\n")
	}

	data, err := renderConfig(initConfigTmpl, answers)
	if err != nil {
		fmt.Fprintf(initStdout, "\n  Error generating config: %v\n", err)
		return 1
	}

	if err := initMkdirAll(dir, 0755); err != nil {
		fmt.Fprintf(initStdout, "\n  Error creating directory %s: %v\n", dir, err)
		fmt.Fprintln(initStdout, "  Hint: try running with sudo if writing to /etc/ratatosk/")
		return 1
	}

	tokenWasAbsent := false
	if answers.RemoteControl {
		_, statErr := initStat(answers.ControlTokenFile)
		tokenWasAbsent = errors.Is(statErr, fs.ErrNotExist)
		if err := initWriteFile(answers.ControlTokenFile, tokenData, fs.FileMode(0600)); err != nil {
			fmt.Fprintf(initStdout, "\n  Error writing control token file: %v\n", err)
			fmt.Fprintln(initStdout, "  Hint: try running with sudo if writing to /etc/ratatosk/")
			return 1
		}
	}

	if err := initWriteFile(outPath, data, fs.FileMode(0600)); err != nil {
		if answers.RemoteControl && tokenWasAbsent {
			if cleanupErr := initRemoveFile(answers.ControlTokenFile); cleanupErr != nil && !errors.Is(cleanupErr, fs.ErrNotExist) {
				fmt.Fprintf(initStdout, "  Warning: could not clean up control token file %s: %v\n", answers.ControlTokenFile, cleanupErr)
			}
		}
		fmt.Fprintf(initStdout, "\n  Error writing config: %v\n", err)
		fmt.Fprintln(initStdout, "  Hint: try running with sudo if writing to /etc/ratatosk/")
		return 1
	}

	fmt.Fprintln(initStdout, "")
	fmt.Fprintln(initStdout, "  =======================================")
	fmt.Fprintln(initStdout, "  Configuration saved successfully!")
	fmt.Fprintln(initStdout, "  =======================================")
	fmt.Fprintln(initStdout, "")
	fmt.Fprintf(initStdout, "  Config file: %s\n", outPath)
	if answers.RemoteControl {
		fmt.Fprintf(initStdout, "  Control token file: %s\n", answers.ControlTokenFile)
	}
	fmt.Fprintln(initStdout, "")
	fmt.Fprintln(initStdout, "  Next steps:")
	fmt.Fprintln(initStdout, "    1. Make sure your DNS records are configured")
	fmt.Fprintln(initStdout, "    2. Open the public proxy port (normally 443/tcp)")
	fmt.Fprintln(initStdout, "    3. Start the server:")
	fmt.Fprintln(initStdout, "         sudo systemctl enable --now ratatosk")
	fmt.Fprintln(initStdout, "    4. Verify it's running:")
	fmt.Fprintln(initStdout, "         sudo systemctl status ratatosk")
	fmt.Fprintln(initStdout, "")
	return 0
}
