package main

import (
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/charmbracelet/huh"
)

var (
	initGetEUID                    = func() int { return os.Geteuid() }
	initWriteFile                  = os.WriteFile
	initMkdirAll                   = os.MkdirAll
	initStat                       = os.Stat
	initRunForm                    = func(f *huh.Form) error { return f.Run() }
	initConfirmOverwrite           = confirmOverwrite
	initStdout           io.Writer = os.Stdout
)

func confirmOverwrite(path string) (bool, error) {
	var overwrite bool
	form := huh.NewForm(
		huh.NewGroup(
			huh.NewConfirm().
				Title(fmt.Sprintf("Config file already exists at %s. Overwrite?", path)).
				Affirmative("Yes").
				Negative("No").
				Value(&overwrite),
		),
	)
	if err := initRunForm(form); err != nil {
		return false, err
	}
	return overwrite, nil
}

type initAnswers struct {
	BaseDomain  string
	TLSAuto     bool
	TLSEmail    string
	TLSProvider string
	TLSAPIToken string
}

const configTemplate = `# Ratatosk Relay Server Configuration
# Generated by: ratatosk-server init
# Full reference: https://ragnarok22.github.io/ratatosk/reference/configuration

base_domain: {{ .BaseDomain }}
public_port: {{ if .TLSAuto }}443{{ else }}8080{{ end }}
admin_port: 8081
control_port: 7000
{{ if .TLSAuto }}
# Automatic TLS via Let's Encrypt DNS-01 (managed by certmagic)
tls_auto: true
tls_email: {{ .TLSEmail }}
tls_provider: {{ .TLSProvider }}
tls_api_token: {{ .TLSAPIToken }}
{{ else }}
# TLS is disabled. To enable automatic TLS, run 'ratatosk-server init' again
# or edit this file manually.
# See: https://ragnarok22.github.io/ratatosk/guide/deployment
tls_auto: false
{{ end }}# Port range for TCP/UDP tunnel allocation
port_range_start: 10000
port_range_end: 20000
`

func renderConfig(answers initAnswers) ([]byte, error) {
	tmpl, err := template.New("config").Parse(configTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing config template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, answers); err != nil {
		return nil, fmt.Errorf("rendering config: %w", err)
	}
	return buf.Bytes(), nil
}

func configDir() string {
	if initGetEUID() == 0 {
		return "/etc/ratatosk"
	}
	return "."
}

func runInit() int {
	fmt.Fprintln(initStdout, "")
	fmt.Fprintln(initStdout, "  Ratatosk Server Setup Wizard")
	fmt.Fprintln(initStdout, "  ============================")
	fmt.Fprintln(initStdout, "")

	var answers initAnswers

	form := huh.NewForm(
		huh.NewGroup(
			huh.NewInput().
				Title("What is your base domain?").
				Description("Tunnels will be accessible at <subdomain>.<domain>").
				Placeholder("tunnel.example.com").
				Value(&answers.BaseDomain).
				Validate(func(s string) error {
					s = strings.TrimSpace(s)
					if s == "" {
						return fmt.Errorf("domain is required")
					}
					if !strings.Contains(s, ".") {
						return fmt.Errorf("enter a valid domain (e.g., tunnel.example.com)")
					}
					return nil
				}),
		),
		huh.NewGroup(
			huh.NewConfirm().
				Title("Enable automatic wildcard TLS via Let's Encrypt?").
				Description("Highly recommended for production. Requires a Cloudflare API token.").
				Affirmative("Yes").
				Negative("No").
				Value(&answers.TLSAuto),
		),
		huh.NewGroup(
			huh.NewInput().
				Title("What is your email address?").
				Description("Used for Let's Encrypt certificate expiry notices").
				Placeholder("you@example.com").
				Value(&answers.TLSEmail).
				Validate(func(s string) error {
					s = strings.TrimSpace(s)
					if s == "" {
						return fmt.Errorf("email is required for Let's Encrypt")
					}
					if !strings.Contains(s, "@") {
						return fmt.Errorf("enter a valid email address")
					}
					return nil
				}),
			huh.NewSelect[string]().
				Title("Select your DNS provider").
				Description("Used to solve DNS-01 challenges for wildcard certificates").
				Options(
					huh.NewOption("Cloudflare", "cloudflare"),
				).
				Value(&answers.TLSProvider),
			huh.NewInput().
				Title("Paste your API token for the DNS provider").
				Description("For Cloudflare: create a token with Zone:DNS:Edit permissions").
				EchoMode(huh.EchoModePassword).
				Value(&answers.TLSAPIToken).
				Validate(func(s string) error {
					if strings.TrimSpace(s) == "" {
						return fmt.Errorf("API token is required for automatic TLS")
					}
					return nil
				}),
		).WithHideFunc(func() bool { return !answers.TLSAuto }),
	)

	if err := initRunForm(form); err != nil {
		if err == huh.ErrUserAborted {
			fmt.Fprintln(initStdout, "\n  Setup cancelled.")
			return 0
		}
		fmt.Fprintf(initStdout, "\n  Error: %v\n", err)
		return 1
	}

	answers.BaseDomain = strings.TrimSpace(answers.BaseDomain)
	answers.TLSEmail = strings.TrimSpace(answers.TLSEmail)
	answers.TLSAPIToken = strings.TrimSpace(answers.TLSAPIToken)

	data, err := renderConfig(answers)
	if err != nil {
		fmt.Fprintf(initStdout, "\n  Error generating config: %v\n", err)
		return 1
	}

	dir := configDir()
	outPath := filepath.Join(dir, "ratatosk.yaml")

	if _, err := initStat(outPath); err == nil {
		overwrite, err := initConfirmOverwrite(outPath)
		if err != nil {
			fmt.Fprintf(initStdout, "\n  Error: %v\n", err)
			return 1
		}
		if !overwrite {
			fmt.Fprintln(initStdout, "\n  Keeping existing config file.")
			return 0
		}
	}

	if err := initMkdirAll(dir, 0755); err != nil {
		fmt.Fprintf(initStdout, "\n  Error creating directory %s: %v\n", dir, err)
		fmt.Fprintln(initStdout, "  Hint: try running with sudo if writing to /etc/ratatosk/")
		return 1
	}

	if err := initWriteFile(outPath, data, fs.FileMode(0600)); err != nil {
		fmt.Fprintf(initStdout, "\n  Error writing config: %v\n", err)
		fmt.Fprintln(initStdout, "  Hint: try running with sudo if writing to /etc/ratatosk/")
		return 1
	}

	fmt.Fprintln(initStdout, "")
	fmt.Fprintln(initStdout, "  =======================================")
	fmt.Fprintln(initStdout, "  Configuration saved successfully!")
	fmt.Fprintln(initStdout, "  =======================================")
	fmt.Fprintln(initStdout, "")
	fmt.Fprintf(initStdout, "  Config file: %s\n", outPath)
	fmt.Fprintln(initStdout, "")
	fmt.Fprintln(initStdout, "  Next steps:")
	fmt.Fprintln(initStdout, "    1. Make sure your DNS records are configured")
	fmt.Fprintln(initStdout, "    2. Open firewall ports: 443/tcp, 7000/tcp, 8081/tcp")
	fmt.Fprintln(initStdout, "    3. Start the server:")
	fmt.Fprintln(initStdout, "         sudo systemctl enable --now ratatosk")
	fmt.Fprintln(initStdout, "    4. Verify it's running:")
	fmt.Fprintln(initStdout, "         sudo systemctl status ratatosk")
	fmt.Fprintln(initStdout, "")
	return 0
}
